#My first Configuration file for Travis CI
language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t  simple_node_travis_ci  .
  - docker tag  simple_node_travis_ci  udoeng/simple-node-travis-ci:latest

after_success:
  - docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
  - docker push udoeng/simple-node-travis-ci:latest
